### ISSUE TITLE
multiple AuthKey support

### ISSUE THREAD

**Issue by emrahcetiner** [ignas-sakalauskas/CustomAuthenticationNetCore#1]
multiple AuthKey can be set. AuthKey should be array.

**Comment by ignas-sakalauskas** [comment]
@emrahcetiner thanks for suggesting multiple AuthKey support, I will add it over the weekend. 
If multiple keys are detected in the Authorization header, and at least one of them was not found in the AuthKey list, then the authentication will fail (strict approach). Is that OK?

**Comment by emrahcetiner** [comment]
absolutely. this solution looks nice.

**Comment by ignas-sakalauskas** [comment]
Multiple auth keys support is enabled now, just assign an array of strings to options AuthKey property. E.g.
`options.AuthKey = new[] { "custom auth key", "custom auth key2" };`
I've also updated my [blog post](https://ignas.me/tech/custom-authentication-asp-net-core-20/).
