### ISSUE TITLE
Cannot get friendly errors message returned from my api

### ISSUE THREAD

**Issue by iby-dev** [ignas-sakalauskas/CustomAuthenticationNetCore#2]
Hi,

I followed the example laid out in your example and came through to here via your blog post.

I have managed to scaffold something that meats my needs for work but I cannot get any errors messages to be return from the CustomAuthHandler class to the caller.

`return Task.FromResult(AuthenticateResult.Fail("Invalid auth key."));`

All i get is status response of 401 and no reason why. It would be nice to see the message: "Invalid auth key" returned the caller in swagger.

Any chance you could explain how or what this is?

**Comment by ignas-sakalauskas** [comment]
Hi @iby-dev,

Thanks for raising this question. I have one solution to return a custom response body described in this blog post: https://ignas.me/tech/custom-unauthorized-response-body/

Please give it a try.

**Comment by iby-dev** [comment]
Thanks man - that certains looks interesting. I will give it a go - not atm though sorry.

I will share the workaround approach we are using now and you call me which approach is more ideal/better.

Thanks,
